<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categoryNames = [
            "Kasur",
            "Waslap Dewasa",
            "Tisu Basah",
            "Sprei",
            "Sikat Lidah Nia",
            "Walker",
            "Jilbab",
            "Kaos Kaki",
            "Bedong Nia",
            "Jam Tangan Nia",
            "Sikat Botol Nia",
            "Jaket",
            "Bantal Nia",
            "Feeding Set",
            "Singlet Dewasa",
            "Baju Kutung Nia",
            "Pembalut Dewasa",
            "Shampo",
            "Gantungan Baju",
            "Baju Pendek Nia",
            "Nasal Nia",
            "Underwear Anak",
            "Blender",
            "Setelan Nia",
            "Topi Set Nia",
            "Balon Nia",
            "Kelambu Bayi",
            "Selimut Bayi",
            "Gunting Kuku",
            "Stroller",
            "Stiker Nyamuk Nia",
            "Gunting Kuku Nia",
            "F & B",
            "Sabun Cuci Botol",
            "Tempat Bedak Nia",
            "Kain",
            "Perlak Nia",
            "Sarung Bantal",
            "Bouncer",
            "Turban Nia",
            "Jaket Nia",
            "Rak Botol",
            "Celana Panjang",
            "Bantal",
            "Jumper",
            "Underwear Dewasa",
            "Tatakan Makan",
            "Baju Panjang",
            "",
            "Celana Pop Nia",
            "Playgym",
            "Oblong Anak Nia",
            "Baju Panjang Nia",
            "Sofa Bayi",
            "Kaos Kaki Nia",
            "Sarung Tangan",
            "Ban Renang",
            "Bedak",
            "Gigitan",
            "Gurita Anak",
            "Breast Pad",
            "Steril",
            "Slow Cooker",
            "Dus Hampers Nia",
            "Popok Nia",
            "Tempat Bedak",
            "keset Kaki",
            "Perlak",
            "Sarung Bantal Nia",
            "Baby Oil",
            "Dot Bayi Nia",
            "Singlet Anak",
            "Turban",
            "Sendok Garpu",
            "Booster",
            "Celana Pendek",
            "Sabun",
            "Sepatu Nia",
            "Baju Renang",
            "Baby Set",
            "Sofa Bayi Nia",
            "Kelambu Dewasa",
            "Kantong Asi",
            "Botol Nia",
            "Kantong Asi Nia",
            "Kasur Nia",
            "Celana Panjang Dewasa",
            "Gendongan",
            "Handuk",
            "Stiker Nia",
            "Selimut Bayi Nia",
            "Sabun Cuci Baju",
            "Tas Nia",
            "Alas Stroller Nia",
            "Sarung Tangan Nia",
            "Topi Set",
            "Celana Panjang Nia",
            "Ayunan",
            "Oblong Dewasa",
            "Apron Nia",
            "Box Bayi",
            "Hiasan Rambut Anak ",
            "Baby Cream",
            "Thermometer Nia",
            "Nasal",
            "Gift Set",
            "Minyak Telon",
            "Pemanas",
            "Tempat Susu Bubuk",
            "Tas",
            "Penjepit",
            "Saputangan Anak",
            "Breast Pump",
            "Waslap Nia",
            "Gurita Dewasa",
            "Saputangan Dewasa",
            "Masker",
            "Sisir",
            "Celana Pop",
            "Sendok Garpu Nia",
            "Ice Pack",
            "Body Care",
            "Tatakan Makan Nia",
            "Setelan",
            "Baju Kutung",
            "Baby Set Nia",
            "Sepatu",
            "Singlet Anak Nia",
            "Oblong Anak",
            "Baju Pendek",
            "Feeding",
            "Sikat Lidah",
            "Dot Bayi",
            "Mainan Nia",
            "Keranjang Baju",
            "Baby Bather",
            "Apron",
            "Baby Swing",
            "Sisir Nia",
            "Topi Nia",
            "Kertas Kado",
            "Bedong",
            "Carseat",
            "Hiasan Rambut Anak Nia",
            "Bandana Nia",
            "Popok",
            "Kartu Ucapan",
            "Termos",
            "Popok Sekali Pakai",
            "Mainan",
            "Gurita Anak Nia",
            "Bandana",
            "Thermometer",
            "Bak Mandi",
            "Jilbab Nia",
            "Skin Care Nia",
            "Feeding Nia",
            "Gurita Dewasa Nia",
            "Kapas",
            "Botol",
            "Sikat Botol",
            "setelan",
            "kaos kaki",
            "Gendongan Nia",
            "celana panjang",
            "Topi",
            "Gigitan Nia",
            "Waslap Anak"
        ];
        foreach ($categoryNames as $categoryName) {
            Category::firstOrCreate(['category_name' => $categoryName]);
        }
    }
}
